import { Vector3 } from '../lib/three.module.js';
const clean = value => typeof value === 'string' ? [...value.replace(/[\u0000-\u001f\u007f]/g,' ').trim()].slice(0,80).join('') : '';
export class RoomChat {
 constructor(game){
  this.game=game;this.opened=false;this.room='';this.outgoing=[];this.history=[];this.seen=new Set();this.bubbles=new Map();this.unread=0;this.next=0;this.lastSent=0;
  const style=document.createElement('style');style.textContent=`
  #chatToggle{position:fixed;left:50%;transform:translateX(-50%);bottom:108px;z-index:12;border:1px solid #97b9ff;border-radius:18px;background:#151e32ed;color:#e1ecff;padding:7px 13px;font:13px sans-serif;cursor:pointer}
  #roomChat{position:fixed;right:12px;bottom:12px;z-index:65;width:min(360px,calc(100vw - 24px));max-height:calc(100dvh - 24px);background:#131626f5;color:#eef2ff;border:1px solid #95bbff;border-radius:14px;box-shadow:0 8px 30px #0008;font:14px sans-serif;overflow:hidden;display:flex;flex-direction:column}
  #roomChat[hidden],#chatToggle[hidden]{display:none}
  #roomChat header{display:flex;align-items:center;justify-content:space-between;padding:10px 12px;border-bottom:1px solid #41485f}#roomChat button{color:#eff6ff;background:#33476b;border:1px solid #7c9fce;border-radius:8px;padding:8px 12px;cursor:pointer}
  #chatHistory{overflow-y:auto;overscroll-behavior:contain;touch-action:pan-y;padding:8px 12px;min-height:50px;height:180px;flex:1;white-space:pre-wrap;overflow-wrap:anywhere}#chatHistory p{margin:0 0 9px;padding:7px 9px;background:#293247;border-radius:9px}#chatHistory b{font-size:11px;color:#b5d8ff;display:block;margin-bottom:3px}#chatHistory time{font-size:10px;color:#a0a6b8;margin-left:6px}
  #chatForm{display:flex;gap:6px;padding:8px 10px}#chatInput{min-width:0;flex:1;font-size:16px;padding:9px;border-radius:8px;border:1px solid #8295b9;background:#0d1321;color:white;user-select:text;-webkit-user-select:text;touch-action:manipulation}#chatNote{font-size:11px;color:#bec8dc;padding:0 12px 10px}
  .playerChatBubble{position:fixed;z-index:11;pointer-events:none;max-width:220px;transform:translate(-50%,-100%);padding:7px 10px;background:#f3f7fff5;color:#1d2340;border:1px solid #8799be;border-radius:12px;box-shadow:0 2px 8px #0005;font:14px/1.4 sans-serif;overflow-wrap:anywhere;white-space:pre-wrap}.playerChatBubble:after{content:'';position:absolute;left:calc(50% - 6px);bottom:-7px;border-top:7px solid #f3f7ff;border-left:6px solid transparent;border-right:6px solid transparent}.playerChatBubble strong{display:block;color:#526b98;font-size:10px}
  @media(max-height:500px){#roomChat{width:330px}#chatHistory{height:110px}#chatToggle{bottom:86px;padding:5px 12px}}
  `;document.head.appendChild(style);
  this.toggle=document.createElement('button');this.toggle.id='chatToggle';this.toggle.type='button';this.toggle.hidden=true;this.toggle.textContent='💬 チャット';this.toggle.setAttribute('aria-controls','roomChat');document.body.appendChild(this.toggle);
  this.panel=document.createElement('section');this.panel.id='roomChat';this.panel.hidden=true;this.panel.setAttribute('aria-label','部屋のチャットと履歴');this.panel.innerHTML=`<header><b>💬 部屋のチャット・履歴</b><button id="chatClose" type="button" aria-label="チャットを閉じる">閉じる</button></header><div id="chatHistory" role="log" aria-live="polite"></div><form id="chatForm"><input id="chatInput" maxlength="80" autocomplete="off" placeholder="メッセージを入力" aria-label="メッセージ"><button type="submit">送信</button></form><div id="chatNote" role="status">80文字まで・吹き出し8秒・履歴100件（退室で消去）</div>`;document.body.appendChild(this.panel);
  this.input=this.panel.querySelector('input');this.log=this.panel.querySelector('#chatHistory');this.note=this.panel.querySelector('#chatNote');
  this.toggle.onclick=()=>this.open();this.panel.querySelector('#chatClose').onclick=()=>this.close();this.panel.querySelector('form').onsubmit=e=>{e.preventDefault();this.send();};
  this.panel.addEventListener('keydown',e=>{e.stopPropagation();if(e.isComposing||e.keyCode===229)return;if(e.code==='Escape'){e.preventDefault();this.close();}});
  this.input.addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.isComposing||e.keyCode===229))e.preventDefault();});
  this.panel.addEventListener('wheel',e=>e.stopPropagation());this.panel.addEventListener('touchmove',e=>e.stopPropagation());
  addEventListener('keydown',e=>{if(e.code==='Enter'&&!e.isComposing&&!this.opened&&game.started&&game.net.on&&!game.paused&&!game.ui.craftOpen&&!/INPUT|TEXTAREA/.test(e.target.tagName)){e.preventDefault();e.stopImmediatePropagation();this.open();}},true);
  this.timer=setInterval(()=>this.update(),100);
 }
 release(){const g=this.game;g.input.keys.clear();g.input.pressed.clear();g.input.axisX=g.input.axisZ=g.input.mouseDX=g.input.mouseDY=0;g.input.dash=false;g.touch?.release();}
 open(){if(!this.game.net.on)return;const room=this.game.net.code+':'+this.game.net.pid;if(room!==this.room)this.reset(room);this.opened=true;this.panel.hidden=false;this.toggle.setAttribute('aria-expanded','true');this.game.input.unlock();this.release();this.unread=0;this.render();this.input.focus();}
 close(){this.opened=false;this.panel.hidden=true;this.toggle.setAttribute('aria-expanded','false');this.input.blur();this.release();}
 reset(room){this.close();this.room=room;this.outgoing=[];this.history=[];this.seen.clear();this.unread=0;this.lastSent=0;this.input.value='';for(const b of this.bubbles.values())b.el.remove();this.bubbles.clear();this.render();}
 send(){const n=this.game.net;if(!n.on){this.note.textContent='部屋に入ってから送信してください';return;}const text=clean(this.input.value);if(!text)return;const now=Date.now();if(now-this.lastSent<1000){this.note.textContent='少し待ってから送信してね';return;}this.lastSent=now;const message={i:++this.next,t:now,text};this.outgoing.push(message);if(this.outgoing.length>30)this.outgoing.shift();this.accept(n.pid,n.name,message);this.input.value='';this.note.textContent='送信しました（通信状態により届くまで少し時間がかかります）';this.input.focus();}
 accept(pid,name,m){if(!m||!Number.isSafeInteger(m.i)||m.i<1||!Number.isFinite(m.t))return;const text=clean(m.text),key=pid+':'+m.i;if(!text||this.seen.has(key))return;this.seen.add(key);if(this.seen.size>2000)this.seen.delete(this.seen.values().next().value);const msg={pid,name:clean(name)||'ともだち',text,t:m.t};this.history.push(msg);this.history.sort((a,b)=>a.t-b.t);if(this.history.length>100)this.history.shift();if(!this.opened&&pid!==this.game.net.pid)this.unread++;
  // 古い履歴を再受信しても、過去の吹き出しをもう一度表示しない。
  if(Date.now()-m.t<8000&&m.t<Date.now()+30000){let b=this.bubbles.get(pid);if(!b){const el=document.createElement('div');el.className='playerChatBubble';document.body.appendChild(el);b={el};this.bubbles.set(pid,b);}if(!b.t||m.t>=b.t){b.t=m.t;b.until=Date.now()+8000;b.el.replaceChildren();const label=document.createElement('strong');label.textContent=msg.name;b.el.append(label,document.createTextNode(text));}}
  this.render();
 }
 render(){const bottom=this.log.scrollHeight-this.log.scrollTop-this.log.clientHeight<35;this.log.replaceChildren();if(!this.history.length){this.log.textContent='この部屋での会話がここに残ります。';return;}for(const m of this.history){const row=document.createElement('p'),name=document.createElement('b'),time=document.createElement('time');name.textContent=m.name;time.textContent=new Date(m.t).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'});name.append(time);row.append(name,document.createTextNode(m.text));this.log.append(row);}if(bottom)this.log.scrollTop=this.log.scrollHeight;}
 update(){const g=this.game,n=g.net,room=n.on?n.code+':'+n.pid:'';if(room!==this.room)this.reset(room);this.toggle.hidden=!n.on||!g.started;this.toggle.textContent='💬 チャット'+(this.unread?'（'+Math.min(99,this.unread)+'）':'')+' · Enter';if(!n.on)return;for(const [pid,p] of n.peers)if(Array.isArray(p.chat))for(const m of p.chat.slice(-30))this.accept(pid,p.name,m);
  const now=Date.now();for(const [pid,b] of this.bubbles){if(now>b.until){b.el.remove();this.bubbles.delete(pid);continue;}const p=pid===n.pid?g.player:n.peers.get(pid);if(!p){b.el.hidden=true;continue;}const v=new Vector3(p.x,p.y+.75,p.z).project(g.camera);b.el.hidden=v.z<-1||v.z>1||Math.abs(v.x)>1||Math.abs(v.y)>1;if(!b.el.hidden){b.el.style.left=(v.x*.5+.5)*innerWidth+'px';b.el.style.top=(-v.y*.5+.5)*innerHeight+'px';}}
 }
}
